name: SonarCloud

on:
  push:
    branches:
      - main  
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and Analyze
    runs-on: windows-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up JDK 17 
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Project
        run: |
          mkdir -p bin
          javac -d bin $(find src -name "*.java")
        shell: bash

      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.projectKey=SimoneCanapini11_Match_analyzer
            -Dsonar.organization=simonecanapini11 
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.java.binaries=bin
            -Dsonar.sources=builder/src
        env:
          GIT_HUB_TOKEN: ${{ secrets.GIT_HUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
